name: Coding Style Checker

on: [ workflow_call ]

jobs:
  Style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Launch coding style
      run: check.sh $(pwd)/src $(pwd)

    - name: Check coding style
      run: |
        if [ -s "coding-style-reports.log" ]; then
            while read -r line; do
            file="${line%%:*}"
            title=${line: -10}
            line_n=$(echo "$line" | cut -d ':' -f 2)
            echo "::error file=${file:2},line=${line_n},title=${title:0:5} coding style error::${line: -4}"
            done < coding-style-reports.log
            exit 333
        else
            exit 0
        fi