name: compile

on: [ workflow_call ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: compile
        run: |
          make fclean && make
        timeout-minutes: 5

